### ISSUE TITLE
object from json

### ISSUE THREAD

**Issue by biskit** [editfmah/sharkorm#10]
is there a straightforward way to load an object from json using reflection?

**Comment by editfmah** [comment]
Because it is just an object, any normal methods or existing frameworks can be used.

That said, we have a roadmap item due for 2 versions time which would allow the setting and getting of values by dictionary which would achieve the same thing.

**Comment by biskit** [comment]
i want to try it with lyft/mapper once i can have an universal build with intel/arm in the library!

**Comment by editfmah** [comment]
Dealt with with feature for up-coming version.  Allows the population of an object on init with a dictionary.
