### ISSUE TITLE
Does Apple reject the SharkORM app because it has sqlite.c source code which contains the dlopen dlsym api?

### ISSUE THREAD

**Issue by melochale** [editfmah/sharkorm#107]
I developed a app which linked the SharkORM and submitted to the Apple, it gave me a message as following:
> Your app, extension, or linked framework appears to contain code designed explicitly with the capability to change your app’s behavior or functionality after App Review approval, which is not in compliance with App Store Review Guideline 2.5.2 and section 3.3.2 of the Apple Developer Program License Agreement.

> This code, combined with a remote resource, can facilitate significant changes to your app’s behavior compared to when it was initially reviewed for the App Store. While you may not be using this functionality currently, it has the potential to load private frameworks, private methods, and enable future feature changes. This includes any code which passes arbitrary parameters to dynamic methods such as dlopen(), dlsym(), respondsToSelector:, performSelector:, method_exchangeImplementations(), and running remote scripts in order to change app behavior and/or call SPI, based on the contents of the downloaded script. Even if the remote resource is not intentionally malicious, it could easily be hijacked via a Man In The Middle (MiTM) attack, which can pose a serious security vulnerability to users of your app.

> The next submission of this app may require a longer review time, and this app will not be eligible for an expedited review until this issue is resolved.

I heard the respondsToSelector/method_exchangeImplementations/performSelector will be acceptable 
if we don' t use the dynamic remote loading feature, so I searched the entire project only the sqlite.c has the dlopen and dlsym api. what am i supposed to do?

**Comment by editfmah** [comment]
We have not had any apps rejected for using that call.  Did you get any further information from Apple regarding this, because we have many apps in the store and recent ones too which use shark and have passed no issue.

**Comment by melochale** [comment]
We appealed and explained what's going on about the library (sharkorm) we used, apple approved it. thanks.
