### ISSUE TITLE
Object show values on debug but returns nil

### ISSUE THREAD

**Issue by daraujofs** [editfmah/sharkorm#113]
I have a class extending SRKObject:
`class Service: SRKObject {
    @objc dynamic var orderId: NSNumber = 0
    @objc dynamic var serviceId: Int32 = 0
    @objc dynamic var desc: String?
    @objc dynamic var minTooth: NSNumber = 0
    @objc dynamic var help: String?
    @objc dynamic var teeth: String?
    @objc dynamic var value: Float = 0.0
    @objc dynamic var quantity: NSNumber = 0
    @objc dynamic var serviceType: NSNumber = 0

    // constructors and methods
    // ...
}`

I receive a JSON from my API and parse to the same object, see the debug with values:
![captura de tela 2018-09-26 as 17 42 23](https://user-images.githubusercontent.com/4997184/46108091-8cc7a100-c1b3-11e8-862e-a65800d17aa6.png)

After this, I just set the value to another object (same type):
`let obj = Service()
        obj.id = service.id
        obj.serviceId = service.serviceId
        obj.desc = service.desc
        obj.help = service.help
        obj.value = service.value
        obj.quantity = NSNumber(integerLiteral: arrayTeeth.count)
        
        for numberTooth in arrayTeeth {
            let tooth = Tooth(number: numberTooth, description: "")
            obj.arrayTeeth.append(tooth)
        }
        
        obj.orderId = Singleton.order!.id!
        obj.commit()`

and the values of "obj"  are nil or the default (0) for numbers:
![captura de tela 2018-09-26 as 17 45 07](https://user-images.githubusercontent.com/4997184/46108241-f051ce80-c1b3-11e8-901e-20fe877870a6.png)

if I try to return the original object, all the values "change" to nil too.

What I'm doing wrong?

**Comment by editfmah** [comment]
It doesn't look like it from the example you posted, but are you setting the values within a swift initialiser, such as init() ?
