### ISSUE TITLE
How to customize properties of the entity table's columns such as type, length

### ISSUE THREAD

**Issue by cityfantom** [editfmah/sharkorm#117]
How to customize properties of the entity table's columns such as type, length

**Comment by editfmah** [comment]
Hi,  the type is determined from the property type.  So a `String` will always be represented by `TEXT` column types, and `Double,Float` will be `REAL` etc....

Length, is irrelevant to SQLite as it always only stores exactly what is bound to the query.  So there are no speed or space savings to be had by specifying limits.  

If you wished to apply limits to get/set then you would need to use custom get/set methods.
