### ISSUE TITLE
Read SQLite database from local bundle using SharkORM

### ISSUE THREAD

**Issue by fichna** [editfmah/sharkorm#119]
I am new in iOS development and I want to read database stored in app bundle with SharkORM. I found getCustomSettings() delegate but I think I'm using it wrong. It creates new DB somewhere else and it is empty.

`@UIApplicationMain
class AppDelegate: UIResponder, UIApplicationDelegate, SRKDelegate {
private static let DatabaseName : String = "data"
private static let DatabaseType : String = "db"

func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool {
    SharkORM.setDelegate(self)
    SharkORM.openDatabaseNamed("data")
    return true
}

// MARK: SharkORM

func getCustomSettings() -> SRKSettings {
    let settings = SRKSettings()
    let databaseURL = URL(fileURLWithPath: Bundle.main.path(forResource: AppDelegate.DatabaseName, ofType: AppDelegate.DatabaseType)!)
    settings.databaseLocation = databaseURL.deletingLastPathComponent().path
    return settings
}
}`

My database file is named data.db and it is stored in `Resources/Database` folder in project.

Can anybody tell me what is wrong? Can anybody provide me working example?

**Comment by editfmah** [comment]
Hi, SharkORM will require R/W access to the database, the reality is that you will need to:

1) Ensure it is a SharkORM compatible database file, e.g. all the property types, names and primary keys match the object model (must have Id PK column).

2) Copy the database out of the bundle into a r/w directory on startup to use it.  R/O is possible, but harder work to achieve.

**Comment by editfmah** [comment]
You could also use the rawExecute function to use an ATTACH command, if the tables are only to be referenced from within queries.

**Comment by shibakaneki** [comment]
Hello,

I was able to do it with SharkORM so I will explain how I did it, maybe it is helpful for you (I am new to iOS development as well by the way!). 
In my XCode project, I just put the SQLite database I want to use in the project files. The key point was to copy this database to the Documents folder of the application in order to move it out from the Bundle, then I can interact with it. This copy is done in the AppDelegate:

```
 func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool {
        let DB_FULL_NAME = DB_NAME + "." + DB_EXTENSION
        
        do{
            let documentsDirectory = try FileManager.default.url(
                for: .documentDirectory,
                in: .userDomainMask,
                appropriateFor:nil,
                create:false)
            
            let dbURL = documentsDirectory.appendingPathComponent(DB_FULL_NAME)
            let fileExists = FileManager().fileExists(atPath: dbURL.path)
            
            if(!fileExists) {
                let databasePath = Bundle.main.url(
                    forResource: DB_NAME,
                    withExtension: DB_EXTENSION)
                
                _ = try FileManager.default.copyItem(at: databasePath!, to:dbURL)
            }

        } catch {
            // TODO: Catch the errors more gracefuly
            print("Couldn't copy the database to the document folder")
        }
        
        // Override point for customization after application launch.
        SharkORM.setDelegate(self)
        SharkORM.openDatabaseNamed(DB_NAME)

        return true
    }
```

It was also necessary to make the database accessible in the project by checking **Target Membership**

<img width="339" alt="capture d ecran 2019-02-15 a 09 20 08" src="https://user-images.githubusercontent.com/738518/52843656-09c3ca80-3103-11e9-86a5-995c32343d2d.png">

I hope that helps!
