### ISSUE TITLE
Cannot read BLOB

### ISSUE THREAD

**Issue by shibakaneki** [editfmah/sharkorm#122]
I would like to read a BLOB column of a table with SharkORM but it always return null for the BLOB column. I know that column contains data (I can see the data with an SQLite viewer). Here is my model:

`import Foundation
import SharkORM

class Entries: SRKObject {
    @objc dynamic var _id = 0
    @objc dynamic var meaning = ""
    @objc dynamic var path : NSData? = nil
    }`

and here is the way I read it:

`let results: SRKResultSet = Entries.query().limit(1).fetch()
        let kana = results[0] as! Entries
        print(kana.path)`

It always returns nil. 

Is it possible to read a BLOB?

Thank you

**Comment by editfmah** [comment]
I'm looking into this now.

**Comment by shibakaneki** [comment]
Thank you!

**Comment by shibakaneki** [comment]
I pushed a bit more my investigation on this issue and here is the response I receive from SharkORM:
`{
	entity = Entries;
	joins =     {};
	"pk column" = Id;
	"pk value" = "<null>";
	properties =     (
		{
			name = path;
			type = unset;
			value = "<null>";
		},
		{
			name = "_id";
			type = number;
			value = 12354;
		},
		{
			name = meaning;
			type = text;
			value = "hiragana a";
		},
		{
			name = Id;
			type = unset;
			value = "<null>";
		}
	);
	relationships =     (
	);
}`

I notice something that may be the key of the issue, I would be happy if someone can confirm my intuition. We can see in the response that the **type** is _unset_ for the path property, maybe this is the cause of the _null_ value.

May it be the reason for always getting _null_?

Here is a screenshot of the table containing the blob (with the query to show how it was created):
<img width="1030" alt="capture d ecran 2019-02-12 a 17 18 55" src="https://user-images.githubusercontent.com/738518/52650349-5ed8c400-2eea-11e9-9f75-2d806197399b.png">

**Edit**
I debugged a bit the code and I noticed that in my case, _sqlite3_column_type_ returns the value **SQLITE_NULL** for the column containing the BLOB. I was expecting it to return **SQLITE_BLOB**, but it doesn't... Maybe the column type cannot be recognized by SharkORM? It recognizes correctly the other column types but not the BLOB one. Is there anything special to know about the SQLite version used for the database or the way to create the BLOB column? Maybe a setting is missing in my DB that SharkORM needs for the BLOB columns?

**Edit 2**
I went as far as I could and I am running out of ideas. In SRKUtilities.m, when the function _sqlite3_column_objc_ is called, there is a call to _sqlite3_column_type_ (row 49 for me). It calls _sqlite3_value_type_ that receives a **pVal** that has the **flags** of value **1** and that causes the type of this column to be interpreted as **SQLITE_NULL**. But in fact it is a BLOB column. Something looks weird at this point (the correct column type is returned for the other columns of this table).

May it be an issue to the encoding of the database? I generate this database with a Ruby script and gives it the **UTF-8 encoding**...

Any idea?

Thank you!

**Comment by editfmah** [comment]
Hi @shibakaneki, are you using CocoaPods?  because I think i've already fixed this in the master branch, but the CocoaPods repo is borked atm so I can't push new versions up.

**Comment by shibakaneki** [comment]
Hi @editfmah , thank you for your follow up! Yes I am using CocoaPods! So it was a known issue that you fixed? I will try with the sources from the master directly then.

What was the reason of this issue by the way?

**Comment by editfmah** [comment]
Hi, there was an error where a dictionary of types was not getting populated fully for some types.  But don't do anything just yet, i'll just check it out here and try and update the CocoaPod now, and see where that gets us.

**Comment by shibakaneki** [comment]
Ok, perfect! Thank you!
