### ISSUE TITLE
pk issue

### ISSUE THREAD

**Issue by biskit** [editfmah/sharkorm#14]
i simply declare a test object from your site page:
class Department : SRKObject {
    dynamic var name: String?
}

and instantiate it in my code (after init in AppDelegate etc).

it crashes immediately like this: looks like its expecting some sorta primary key declaration? would have thought its not necessary for sqlite as it automatically creates 'id' or 'ID' as pk.

**\* Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '**\* setObjectForKey: object cannot be nil (key: pk value)'

**Comment by editfmah** [comment]
You will need to send us a sample application that demonstrates this issue, because we don't reference "pk" anywhere.  So we are none the wiser as to where this error is coming from.

**Comment by biskit** [comment]
I'll try to get that to you asap: meantime here's part of stack trace.
**\* First throw call stack:
(
    0   CoreFoundation                      0x000000010a378c65 __exceptionPreprocess + 165
    1   libobjc.A.dylib                     0x000000010c125bb7 objc_exception_throw + 45
    2   CoreFoundation                      0x000000010a27daf8 -[__NSDictionaryM setObject:forKey:] + 968
    3   SharkORM                            0x0000000109df7309 -[SRKObject description] + 345
    4   libswiftFoundation.dylib            0x000000010caaed0b _TTWCSo8NSObjects23CustomStringConvertible10FoundationFS0_g11descriptionSS + 43
    5   libswiftCore.dylib                  0x000000010c6c72f5 _TFs15_print_unlockedu0_R_s16OutputStreamTyperFTxRq__T_ + 949
    6   libswiftCore.dylib                  0x000000010c6a79e0 _TFSSCurfT26stringInterpolationSegmentx_SS + 64

**Comment by editfmah** [comment]
Yep, looks like a bug.  We will get a fix out quickly.  It was a new piece of code that seemed to work okay.  Although we will have to try and replicate still.

**Comment by biskit** [comment]
happy to test it and report!

**Comment by editfmah** [comment]
2.0.5 has now been pushed and that issue should be fixed.
