### ISSUE TITLE
Not all property needs to be saved

### ISSUE THREAD

**Issue by wells1013** [editfmah/sharkorm#16]
```
#param Book.h
@interface Book : SRKObject

@property NSString* name;
@property NSString* author;
@property NSDate* published;
// not need save to sqlite
@property (nonatomic, copy) NSString *comment;
@end

#param Book.m
@implementation Book
@dynamic name,published,author;
@end
```

How to implement without saving the comment field， tks！

**Comment by sharkorm** [comment]
Will take a look now,  we should only be persisting dynamic properties.  Anything else is a bug.

Do you have any swift in your project at all?  Or is it all Obj-C.

**Comment by wells1013** [comment]
no swift, only Obj-C. 
'comment' also be stored in the database

**Comment by editfmah** [comment]
Hi,

v2.0.6 has been released and addresses this issue.

SRKObject’s now implement a class method ‘ignoreProperties’. Which allows developers to choose which properties to ignore.  Return an array of property names and these will not be included within the model.
