### ISSUE TITLE
doesn't support Id with String type

### ISSUE THREAD

**Issue by lbwxly** [editfmah/sharkorm#18]
i have digged into the code and found following, not sure if i am correct:
method +(int)getEntityPropertyType:(NSString*)propertyName in SRKObject doesn't try to find the property in the super class, so each time,when some place need to get the data type of the default primary key Id, the result is the Undefine, then process the primary key as Number by default. so, the type of the Id property define in the SRKObject header file is useless.

**Comment by lbwxly** [comment]
Do it support custom primary key for each class?

**Comment by editfmah** [comment]
No, the primary key is always fixed as "Id".  That said, it is our intention to extend that with a method call to define a different property as the PK value.

We are just looking now, I know that Id is specifically excluded from the building of that dictionary, but I will just check the behaviour when you implement Id as NSString\* in the entity class.

**Comment by editfmah** [comment]
Hi, i've just stepped through our unit test and can see the "Id" is cached as type 2 which is a string.  The table creation is correct for this too.

The exclusions I mentioned earlier were wrong, it was in another part of the code where Id is excluded.

Here is my Class Definition:

```
#import "SharkORM.h"
#import "StringIdRelatedObject.h"

@interface StringIdObject : SRKObject

@property (strong, nonatomic) NSString* Id;
@property (strong) NSString* value;
@property (strong) StringIdRelatedObject* related;

@end

```

And here is the debugger output:

<img width="673" alt="screen shot 2016-07-24 at 15 15 10" src="https://cloud.githubusercontent.com/assets/3480030/17084304/256a698e-51b2-11e6-9b6c-166e987aa922.png">

Is there anything else specific that may help us trace this problem?

**Comment by editfmah** [comment]
Ah, sorry.  I have just re-read your issue, are you saying that everything works okay, but the Id in SRKObject is never inspected and is therefore useless/pointless?

Other than for convenience of it being there?

**Comment by lbwxly** [comment]
sorry, you mean i only define a property named Id and with String type in my class, then i can use string primary key?
i am using swift, i cant define that property, compiler give me a conflict error.

**Comment by lbwxly** [comment]
/Users/Jensen/Documents/Project/TechnicalTest/SharkSample/SharkSample/Company.swift:13:33: Property 'Id' with type 'String!' cannot override a property with type 'NSNumber!'

**Comment by editfmah** [comment]
Ah, swift.  Let me just look at how that can be achieved.

**Comment by editfmah** [comment]
Okay, so this doesn't look very easy to fix.  Swift does not allow any kind of shenanigans with the overloads of properties.  So the options to fix this are as follows:

1) create another property and index it so it performs and largely behaves the same as the pk.
2) create another obj-c subclass of SRK object which has an NSString\* Id property.
3) remove Id from SRKObject, and make everyone add it into their implementations.
