### ISSUE TITLE
Support complex query

### ISSUE THREAD

**Issue by lbwxly** [editfmah/sharkorm#19]
I have following structure.
public class Address:SRKObject
{
   dynamic var city:String?
}
public class Company:SRKObject
{
    dynamic var name:String?
    dynamic var address:Address?
}

Does it support following query:
Company.query().where("address.city = 'NewYork' ").fetch()

**Comment by editfmah** [comment]
Hi,

Yes it does.  This can be achieved one of two ways, the first being a subquery (which SQLite does an excellent job of optimising).

`Company.query().whereWithFormat("address IN (SELECT Id FROM Address where city = 'NewYork') ", withParameters: nil).fetch()`

The second is with a join, which leaves the query more like your original example.
`
Company.query().whereWithFormat("Address.city = 'New York' ", withParameters: nil).joinTo(Address.self, leftParameter: "address", targetParameter: "Id").fetch()
`
This, will then give you access to the Address table to specify a query parameter.

No one has ever contacted us with the suggestion of object.notation within the query parameters before, but it seems logical.  We will look into implementing this as it will be a simple case of just looking for '(SRKObject>).(PropertyName>)', and then automatically creating and naming the joins.

Thanks
Adrian

**Comment by lbwxly** [comment]
got it, thank you!

**Comment by editfmah** [comment]
Hi,

I've just check in a patch that supports object dot notation within query and order by conditions, so your query " address.city = 'New York' " will now work.

So if you want to pull down the code checked in on master, you will now be able to query in this manner.

Thanks
Adrian

**Comment by lbwxly** [comment]
ok, thanks for your fixing.

**Comment by lbwxly** [comment]
does order by clause support the same query?
e.g. Company.query().whereWithFormat("address IN (SELECT Id FROM Address where city = 'NewYork') ", withParameters: nil).orderBy("address.city").fetch() ?

**Comment by lbwxly** [comment]
i have a try on following:
Compnay.query().orderBy("Address.city").joinTo(Address.self,"address","Id").fetch().
it work.

**Comment by editfmah** [comment]
Yes it certainly should do.

**Comment by editfmah** [comment]
It won't work for the subquery, because the tables are not joined.  As you said it works for the join.

But if you pull the latest code, you don't need to join and you can use the order by too.

e.g. Company.query().whereWithFormat("address.city = 'NewYork' ", withParameters: nil).orderBy("address.city").fetch() ?

**Comment by lbwxly** [comment]
got it. it is great that i can get help from the author when i use the library. Thank you very much! I plan to learn your source code carefully.

**Comment by editfmah** [comment]
No problem.

**Comment by lbwxly** [comment]
Do you have any detail document about the source code? like sequence diagram, class diagram...

**Comment by editfmah** [comment]
This is the documentation for the original project, unfortunately SharkORM crashes Doxygen so we can't produce a more up to date version yet.

http://docs.db-access.org/hierarchy.html
