### ISSUE TITLE
is there any way to support like statement?

### ISSUE THREAD

**Issue by lbwxly** [editfmah/sharkorm#23]
public class Address:SRKObject
{
    var city:String!;
    var state:String!;
}

is there any way to support following query: Address.query().where("city like '%new%'").fetch()?

**Comment by editfmah** [comment]
Yeah sure,

So in Objective-C it's
 SRKResultSet *r = [[Person query] whereWithFormat:@"Name LIKE %@", makeLikeParameter(@"cha")].fetch;

So in swift it will be something like:
Address.query().whereWithParameters("city LIKE %@", parameters:[makeLikeParameter("lon")]).fetch();

Thanks

**Comment by editfmah** [comment]
See this for a better example:  (except the function name has changed)

http://stackoverflow.com/questions/37270748/ios-dbaccess-query-debug

**Comment by lbwxly** [comment]
got it. it work fine, thank you for your quick reply. thanks!
