### ISSUE TITLE
NSDate property can not be saved in transaction

### ISSUE THREAD

**Issue by lbwxly** [editfmah/sharkorm#25]
----model defination
public class Company : SRKStringObject
{
    dynamic var name:String?;
    dynamic var address:Address?;

```
dynamic var foundDate:NSDate?

public dynamic var displayName : String? {
    return name! + " " + (address?.city)!;
}
```

}

public class Address:SRKStringObject
{
    dynamic var city:String?
}
---data storage call
SRKTransaction.transaction({ 
            let address = Address();
            address.city = "Shanghai";
            let company1 = Company();
            company1.name = "PKI";
            company1.address = address;
            company1.foundDate = NSDate();
            company1.commit();
            }, withRollback: nil);

the result is the found date is not saved into database.

**Comment by editfmah** [comment]
We will take a look now.

**Comment by lbwxly** [comment]
hi, any update for the issue?

**Comment by editfmah** [comment]
This has now been fixed in the master branch.

**Comment by editfmah** [comment]
Hi @lbwxly ,

Another developer has just found another bug in NSDate retrieval, so there will be another fix you may wish to pull down if you are seeing weird behaviour.

Thanks

**Comment by lbwxly** [comment]
got it, i will get the latest code.
