### ISSUE TITLE
json array importing

### ISSUE THREAD

**Issue by Sebacho-Barajas** [editfmah/sharkorm#33]
i'm trying to import an array of objects to the database but when i'm going to check the db file the results I get are "BLOB" is there a way I can import multiple objects from json to the db?

**Comment by editfmah** [comment]
I'm not sure what kind of method you are using to import any of the data, as there is no native json import routine.

The way it is advantageous to do it, is to iterate the JSON objects and create the SRKObject's for your class and then populate the matching properties.  Then commit them into the database.

If you supply more detail as to how you are going about inserting all the values into the db now, then we may be able to provide more help.

**Comment by Sebacho-Barajas** [comment]
hi this are my screenshots
categories.h
![screen shot 2016-10-05 at 10 28 10 pm](https://cloud.githubusercontent.com/assets/10381993/19138597/9d03f55a-8b4b-11e6-81cc-a4042e99ce54.png)
categories.m
![screen shot 2016-10-05 at 10 28 28 pm](https://cloud.githubusercontent.com/assets/10381993/19138612/cbb90afc-8b4b-11e6-8797-a426bac7cec5.png)

this is what I got from afnetworking in the appdelegate 

![screen shot 2016-10-05 at 10 31 30 pm](https://cloud.githubusercontent.com/assets/10381993/19138634/f2b9378a-8b4b-11e6-848f-d88dd1f9e9af.png)

and this is what I get in the database 
![screen shot 2016-10-05 at 10 35 40 pm](https://cloud.githubusercontent.com/assets/10381993/19138647/1d3c3886-8b4c-11e6-897d-c9f2ef927512.png)

**Comment by Sebacho-Barajas** [comment]
this are some of the results I get when I log into "newCategories.categoryID"
Category ID results:(
    1,
    2,
    5,
    6,
    7,
    8,
    9,
    11
)

**Comment by editfmah** [comment]
Sorry for the delay, i've been travelling.  Your code looks good, and I can't see any problems with it.  One thing I would try is if you break and the po the object before and after commit.  I'd be interested to see what the object thinks it contains.

**Comment by editfmah** [comment]
No response from poster so closing.  Can be re-opened if still a problem.
