### ISSUE TITLE
How can i setup a query to get all objects whose specify property value is null

### ISSUE THREAD

**Issue by lbwxly** [editfmah/sharkorm#34]
I try following code, but failed.
Company.query().whereWithFormat("name = %@",[NSNull()]).fetch();

**Comment by editfmah** [comment]
Hi,

It's the same as SQLite, so it would be Company.query().whereWithFormat("name IS NULL",[]).fetch();

**Comment by lbwxly** [comment]
got it, thank you.

**Comment by lorenzoPrimi** [comment]
@editfmah I don't open a new issue as I have a very similar one.
I need to do a similar query inside a SRKObject, and some values of this object can be null, so this code will crash:
```SRKQuery *query = [[Network query] where:@"network_name = ? AND ip = ? AND asn = ? AND country_code = ? AND network_type = ?" parameters:@[self.network_name, self.ip, self.asn, self.country_code, self.network_type]];```

How to solve it? I tried to make the getter returning "NULL" in case the var is null but it doesn't seem to work
