### ISSUE TITLE
fts_ table issue 

### ISSUE THREAD

**Issue by Parkyprg** [editfmah/sharkorm#39]
I am always receiving errors on fts tables, like the following:

INSERT INTO fts_Contact(docid, ) SELECT Id,  FROM Contact WHERE Id = 841
near ")": syntax error

First of all, I don't see any fts_ tables in my db and also FTSRegistry is empty.
Is there something I missed?

**Comment by editfmah** [comment]
Nope, if you are not using the FTS table then these queries should not be getting run.  I'll forward you a chuck of code, if you wouldn't mind dropping a breakpoint on it, i'd love to know why it's getting called or at least which path is being taken to end up there.

**Comment by Parkyprg** [comment]
Didn't received the code. 

I am not calling FTSParametersForEntity in my classes.
However, lately, I am not receiving these messages anymore (not sure what changes in my code triggered that). 

But I still see these logs (after startup):
`DROP TABLE fts_%;
no such table: fts_FTS%`

I know you check if the FTS has been turned off, but doesn't have to be each time the application is launched. Maybe keep an upgrade flag somewhere and run these only once.

**Comment by Parkyprg** [comment]
I am still receiving the error but only when I use SRKTransaction.

In SRKTransactionGroup.m, inside commit, right after it succeeded (around line 239), for both event types - SharkORMEventInsert and SharkORMEventUpdate you are not checking to see if there are any FTSParametersForEntity. So this piece of code is getting executed every time, raising a silent error that the fts_% table does not exist:

> ```
>                                   if ([item.originalObject.Id isKindOfClass:[NSNumber class]]) {
>                                       [SharkORM executeSQL:[NSString stringWithFormat:@"INSERT INTO fts_%@(docid, %@) SELECT Id, %@ FROM %@ WHERE Id = %@", [[item.originalObject class] description],propertiesList,propertiesList, [[item.originalObject class] description], [item.originalObject getField:SRK_DEFAULT_PRIMARY_KEY_NAME]] inDatabase:nil];
>                                   } else {
>                                       [SharkORM executeSQL:[NSString stringWithFormat:@"INSERT INTO fts_%@(docid, %@) SELECT Id, %@ FROM %@ WHERE Id = '%@'", [[item.originalObject class] description],propertiesList,propertiesList, [[item.originalObject class] description], [item.originalObject getField:SRK_DEFAULT_PRIMARY_KEY_NAME]] inDatabase:nil];
>                                   }
> ```

**Comment by editfmah** [comment]
Okay, thanks for that.  We'll get it fixed for the next build.

**Comment by editfmah** [comment]
This has now been fixed in the latest push to master.  It will be included in the release 2.1.0
