### ISSUE TITLE
Swift Compile error: Segmentation fault

### ISSUE THREAD

**Issue by marlonchalegre** [editfmah/sharkorm#41]
I'm using the latest XCode and Swift 3. When I add the SharkORM in my bridging file the Swift compiler crash.

=========== LOG ====================
# include <SharkORM/SharkORM.h>

```
    ^
```

.../Pods/Headers/Public/SharkORM/SharkORM.h:629:34: warning: unknown warning group '-Ww', ignored
# pragma clang diagnostic ignored "-Ww"

```
                             ^
```

.../Pods/Headers/Public/SharkORM/SharkORM.h:631:43: warning: property type 'NSString _' is incompatible with type 'NSNumber *' inherited from 'SRKObject'
@property (nonatomic, strong)   NSString_ Id;
                                          ^
.../Pods/Headers/Public/SharkORM/SharkORM.h:396:43: note: property declared here
@property (nonatomic, strong)   NSNumber\* Id;
                                          ^
0  swift                    0x0000000105dd9b6d PrintStackTraceSignalHandler(void_) + 45
1  swift                    0x0000000105dd95b6 SignalHandler(int) + 470
2  libsystem_platform.dylib 0x00007fffc745abba _sigtramp + 26
3  libsystem_platform.dylib 0x00007fa1f921c1c0 _sigtramp + 836507168
4  swift                    0x00000001037c7ee9 swift::ModuleFile::getType(llvm::PointerEmbeddedInt<unsigned int, 31>) + 857
5  swift                    0x00000001037c3ebd swift::ModuleFile::getDecl(llvm::PointerEmbeddedInt<unsigned int, 31>, llvm::Optional<swift::DeclContext_>) + 32477
6  swift                    0x00000001037ec4ef swift::ModuleFile::getTopLevelDecls(llvm::SmallVectorImplswift::Decl*&) + 3087
7  swift                    0x000000010351f520 swift::SILPassManager::SILPassManager(swift::SILModule_, llvm::StringRef) + 1344
8  swift                    0x00000001035242cf swift::runSILDiagnosticPasses(swift::SILModule&) + 159
9  swift                    0x00000001031ef267 performCompile(swift::CompilerInstance&, swift::CompilerInvocation&, llvm::ArrayRef<char const_>, int&, swift::FrontendObserver_) + 19751
10 swift                    0x00000001031e8265 swift::performFrontend(llvm::ArrayRef<char const_>, char const_, void_, swift::FrontendObserver*) + 17029
11 swift                    0x00000001031a582d main + 8685
12 libdyld.dylib            0x00007fffc724e255 start + 1

**Comment by editfmah** [comment]
Hi, I've just created a Swift3 test application and didn't suffer any crashes during compilation.  Here is my application, and we've not had any reports of this so far.  So could I ask you to check for other things, or complications as it doesn't seem to be quite as straight forward as being a conflict with interfacing with swift3.
[swift3test.zip](https://github.com/sharksync/sharkorm/files/546048/swift3test.zip)

**Comment by marlonchalegre** [comment]
I'll take a look at your code and post any insights. My project is almosts empty I just added the FCM library and code.

**Comment by marlonchalegre** [comment]
Okay, the problem just happens when I use the Firebase and SharkORM at the same time. I do not know if the problem is the compiler, the shark framework or the firebase framework.

If you want to see, just uncomment the "import Firebase" line.
[TestProject.zip](https://github.com/sharksync/sharkorm/files/551079/TestProject.zip)
