### ISSUE TITLE
[Help] Disable auto_increment

### ISSUE THREAD

**Issue by vitorotero** [editfmah/sharkorm#43]
How can I disable auto_increment of primary key or override its value?

When I set value for field that is a primary key, the SharkORM ignore passed value.

My .h file
`@interface PaymentModel : SRKObject`
`@property (nonatomic, strong) NSNumber *id;`
`@property (nonatomic, strong) NSString *name;`
`@property (nonatomic, strong) NSString *status;`
`@end`
and .m file
`@implementation PaymentModel`
`@dynamic id, name, status;`
`@end`

**Comment by Parkyprg** [comment]
Why do you want to disable the default autoincrement of Id field for a SharkORM object?
If you need, you can use your own ID field (NSNumber), where you can specify any value.

**Comment by editfmah** [comment]
@Parkyprg raises a good point in that, ideally, the Id column is used for SharkORM to maintain it's relationships and function.  That way developers can create column names that mirror any kind of service they interact with.

That said, you should be able to specify your own Id value, if this does not work then it will be investigated as a bug.  There were recent changes to the back-store that fixed an issue with the Id column not having the correct default value, it may be that in fixing this issue it have inadvertently broken this feature.

Have you tried using the method:
- (id)initWithPrimaryKeyValue:(NSObject*)priKeyValue

If this does not work then:

a) this is a bug and it will be added to the fix list
b) create another column which achieves what you require.

**Comment by vitorotero** [comment]
@editfmah This method `(id)initWithPrimaryKeyValue:(NSObject*)priKeyValue` not working for me.

It is also a solution for my case `[SharkORM rawQuery:@"DELETE FROM SQLITE_SEQUENCE WHERE NAME = 'PaymentModel'"];`, but, I will create a new column.

**Comment by editfmah** [comment]
Yeah, we'll look into this potential bug (it sounds like it).  But I really wouldn't go deleting stuff from the sequence table if I were you.  There should always be a better way to solve an issue than that.

**Comment by editfmah** [comment]
I don't know if this has been accidentally fixed, but i've searched and tested and just can't see this issue.  Below is the test case, i've tested the output in all the obvious places.

```
- (void)test_specify_own_pk_value {
    
    [self cleardown];
    
    Person * p = [[Person alloc] initWithPrimaryKeyValue:@(1234)];
    [p commit];
    
    XCTAssert(([[[Person query] whereWithFormat:@"Id = %@", @(1234)] count] == 1), @"Primary key that had been specified was not stored as specified in the init function");
    XCTAssert((p.Id.integerValue == 1234), @"Primary key that had been specified was not stored as specified in the init function");
    XCTAssert(([p.description rangeOfString:@"\"pk value\" = 1234;"].location != NSNotFound), @"Primary key that had been specified was not stored as specified in the init function");
    
}
```
