### ISSUE TITLE
Overriding description breaks commit

### ISSUE THREAD

**Issue by hakim89** [editfmah/sharkorm#46]
my models don't get created in the database when i override description value
any ideas ?

```

class Contact:SRKObject {
    
    dynamic var name:String = ""
    dynamic var phoneNumber:String = ""
    
    override var description: String{
        get{
            return "\(self.name) - \(self.phoneNumber)"
        }
    }
}


```

**Comment by editfmah** [comment]
Hi, yes this is an integral part of determining the class name/hierarchy.  But it should only be the class method that we use, the instance method is also used but is not as important to the orm.  I would simply create a method that is not called description (which is reserved in obj-c anyway) and save a whole load of hassle.  Or work out a way to stop swift from replacing the objective-c selectors for the class method when it is quite obviously an instance override.

**Comment by hakim89** [comment]
Thanks for the clarification.
