### ISSUE TITLE
some questions on the database access?

### ISSUE THREAD

**Issue by lbwxly** [editfmah/sharkorm#47]
1. it there any problem if i don't  call closeDatabase method when app exit?
2. consider the situation: SharkORM call begin transaction of sqlite api and write some data, but the app crashed before calling commit transaction statement. how sqlite handle this case?

**Comment by editfmah** [comment]
Hi,

There should be no problem never calling closeDatabase.  We use the ultra safe WAL, so if the application crashes within a transaction then that transaction is automatically rolled back.  All operations are guaranteed to be atomic using the WAL mode journal.

Thanks
