### ISSUE TITLE
How to install on Xcode 8 / Swift 3

### ISSUE THREAD

**Issue by MickL** [editfmah/sharkorm#50]
I was not able to install this. Im pretty new to Xcode.

I drag and dropped the folder "SharkORM" into XCode and selected "Create groups". Then i created a file "Swift-Bridging-Header.h" and typed in `#include “SharkORM.h”`. When i hold CMD and click on it it leads me to the interface declaration(good!?). Now when i try to use it: `class MyClass: SRKObject { ... }` i get an error: "Use of undeclared type 'SRKObject'". But i can CMD+click on it which leads me to the interface declaration again.

I tried to install with Cocoapod, too with no success.

**Comment by editfmah** [comment]
Has the .h file been added into the project settings as the relevant bridging header?

**Comment by editfmah** [comment]
Think this is resolved now, so closing issue.
