### ISSUE TITLE
Is there any suggestion on error handling with Shark library?

### ISSUE THREAD

**Issue by lbwxly** [editfmah/sharkorm#51]
for example,when i call Person.query.fetch(), is there any thing will make this call failed even if the data is there? if it occur, how can i know  the  error occur, it seem that not matter what the calling is succeed or failed, the result won't be null.

**Comment by editfmah** [comment]
Okay, so originally there was no ability to throw errors, and even the current apple implementation is not backwards compatible as far as this framework is.

So, the way errors are caught in development is by adding the **databaseError**: method to your delegate and then setting a breakpoint.  This will stop whenever a syntax error occurs within your query (which is to my knowledge the only way to cause an error).

So in future, we can start to re-shape the framework to throw errors, or embed an error object within the SRKResultSet class, that you can test for should you wish.

Returning nil is a divisive issue amongst people i've spoken too, and was the original way of dealing with an error.  But it doesn't give you any more information, so providing error feedback within the call may be the better plan.

**Comment by lbwxly** [comment]
ok, another improvement i think is about the select statement in the transaction,e.g.:
SRKTransaction.transaction({
    let ids = [1,2,3,4,5];
    var result = Person.query().whereWithFormat("Id in %@", parameters:[ids]).fetch();
    if(result.count == 0) {
           var setting = Setting();
           setting.noPerson = true;
           setting.commit();
    }
}
) withRollback:({
    print("query failed.");
}
);

in this case, the commit operation depends on the result of the first select operation. but in current implementation of shark library,the transaction will continue to process even if select failed (in my case, the count of ids exceed the count limitation of hot parameter in the sqlite). this will produce a invalid data. the select failed should lead a transaction failed here. how do you think this?

**Comment by editfmah** [comment]
Hi @lbwxly,

So I see your issue.  We could change the response to return nil, or look at throwing errors.  In your scenario, more than anything there is more the issue of application logic fouling the simplistic SQL transactions.

So, what I was thinking would be more along the lines of a way to invalidate a transaction for app logic reasons too, this way developers can rollback for any reason whatsoever.  There is already a branch with a re-write of transactions to deal with some performance issues so this feels like it can be added at the same point.

Let me know your thoughts.  Mine are the following:

- Setting for nil return on error

- an abort() function for app logic to cancel a transaction. 

- have results contain an error object, and maybe performance stats as well that can be po'd.

Thanks
Adrian

**Comment by editfmah** [comment]
As a general rule, the design of Shark was to break the standard way of using transactions at all, by preventing all kinds of runtime errors and allowing code to just be used inline as opposed to concentrated in blocks.  So, in short, every effort must be made to ensure that there is no way to generate a runtime error at all, and short of corruption everything would always persist without error.

**Comment by lbwxly** [comment]
I agree with your thought, and i think we can add another setting to indicate if transaction will rollback(rollback call back will be called) when select failed (maybe some error occur). generally, i think in the transaction should be rolled back even if the error occur in select operation. of course, if your set this setting to false, we can ignore it.

**Comment by editfmah** [comment]
This is now fixed, although a future feature will be implemented to switch to throwing meaningful errors generally within the ORM.
