### ISSUE TITLE
Is there anything cached in memory when do the query, is this a way to disable possible large amount cache object?

### ISSUE THREAD

**Issue by lbwxly** [editfmah/sharkorm#53]
in my case, my memory usage is keep in a high value, just to want to know if the library cache something?

**Comment by editfmah** [comment]
No, there is currently no caching mechanism at all in the ORM.  That was removed in port from DBAccess.

**Comment by editfmah** [comment]
Did you find out what it was?

**Comment by lbwxly** [comment]
No, just confirm with you if shark cache some thing. close it because i get answer from you.
