### ISSUE TITLE
Not inherit 

### ISSUE THREAD

**Issue by fordringd2008** [editfmah/sharkorm#59]
Now my model inherit from the JSonModel, and now I want to use this framework, how to do not inherit the SRKObject is the case, the use of ORM function?

**Comment by editfmah** [comment]
@dingfude2008, are you asking how do you use SharkORM but not use it's object class SRKObject?

**Comment by fordringd2008** [comment]
YES, it is

**Comment by editfmah** [comment]
Ah right, at present it is not possible to do this.  We have discussed this around the office and we know this is common in other ORM's on other platforms.  

It is something we will consider for a future version, but at present it would be a non-trivial amount of effort to implement that feature.

**Comment by fordringd2008** [comment]
Thanks
