### ISSUE TITLE
How to use in Swift?

### ISSUE THREAD

**Issue by ahmedk92** [editfmah/sharkorm#6]
I installed sharkorm with cocoapods. However, SRKDelegate is not found when I'm trying to implement it in the app delegate.

**Comment by editfmah** [comment]
Hi,

This is mainly to do with interfacing with objective-c.  You need to add the SharkORM.h file into a bridging header to make it accessible from Swift.

Please see this information below from the Apple site:
https://developer.apple.com/library/ios/documentation/Swift/Conceptual/BuildingCocoaApps/MixandMatch.html

Also here is a sample application that i've just created that solves the problem so you can inspect the setup.

[testapp.zip](https://github.com/sharksync/sharkorm/files/325246/testapp.zip)

Thanks
Adrian

**Comment by ahmedk92** [comment]
Thanks. That did it.
