### ISSUE TITLE
Code defect for previous version(2.0.9)

### ISSUE THREAD

**Issue by lbwxly** [editfmah/sharkorm#62]
@editfmah 
I find the latest version has refactor the transaction model. but i can't update to the latest version in my project for now. And now i found a code defect in the old transaction logic i think my version is 2.0.9 :
the code is in the commit method of the SRKTransactionGroup class, i can't paste all code in the method, just paste key code to point out the defect position:
if (sqlite3_prepare_v2([SharkORM handleForDatabase:databaseNameForClass], [item.statementSQL UTF8String], (int)item.statementSQL.length, &statement, NULL) == SQLITE_OK) {
   // ignore all code here                                            
}
else {
**//succeed = NO; this line is not presented in the source code, i want to add it here.**
											/* error in prepare statement */
	if ([[SRKGlobals sharedObject] delegate] && [[[SRKGlobals sharedObject] delegate] respondsToSelector:@selector(databaseError:)]) {
												
       SRKError* e = [SRKError new];
       e.sqlQuery = item.statementSQL;
       e.errorMessage = [NSString stringWithUTF8String:sqlite3_errmsg(databaseHandle)];
        [[[SRKGlobals sharedObject] delegate] databaseError:e];											
	}
}
in the else branch, the succeed should be set to No to roll back the transaction since error occur.
I plan to make this change in my local code, just confirm with you here to avoid this change will bring some problem.

**Comment by editfmah** [comment]
Yeah, looks like a straightforward bug.  I can't see any problems adding that condition in.
