### ISSUE TITLE
Default values not working on Swift

### ISSUE THREAD

**Issue by Pedroalexandrelopes** [editfmah/sharkorm#64]
I'm trying to add default values to an entity but i'm having problems with swift.

From the docs:
`override class func defaultValuesForEntity() -> [NSObject : AnyObject] {
    return ["name" : "Billy", "age" : 36]
}`

Error: "Method does not override any method from its superclass"
I'm adding it to a SRKObject.

**Comment by editfmah** [comment]
Hi @Pedroalexandrelopes 

It looks like Swift 3 as of XCode 8.2+ requires the following definition.

override class func defaultValuesForEntity() -> [AnyHashable : Any] { return ["name" : "Billy", "age" : 36] }

But don't worry, the swift version is currently under development.  About 1/3 complete as it happens, and then normality can resume and this craziness will be done with!

**Comment by Pedroalexandrelopes** [comment]
That one I didn't try. Seems to be working fine now.
Thank you!
