### ISSUE TITLE
Delegate methods databaseEntryWas* are never called

### ISSUE THREAD

**Issue by btkelly** [editfmah/sharkorm#66]
The `SRKDelegate` methods of `databaseEntityWasInserted`, `databaseEntityWasDeleted`, and `databaseEntityWasUpdated` are never called. When I override the `entityDidInsert` on the model in question this will fire but the delegate methods will not.

For additional information I am using Swift 3 and have set delegate beforehand using `SharkORM.setDelegate(self)` before opening the database.

**Comment by editfmah** [comment]
Implemented new block based methods in v2.1.3.
