### ISSUE TITLE
orderBy chaining with different directions

### ISSUE THREAD

**Issue by mattvb91** [editfmah/sharkorm#67]
Trying to figure out how to use orderBy with multiple columns but also different directions.

For example:

    .order(byDescending: "date").order(by: "id")

Or:

     .order(byDescending: "date, id ASC")

Feel like im just missing something obvious? Order by date first & then by id

Edit:

Ok there seems to be an underlying issue even with just chaining orderBy's for example:
    
    .order(byDescending: "date, id") 

That seems to only order by id and ignore date. @editfmah do you guys have any examples of chaining the orderBy?

**Comment by editfmah** [comment]
Hi Matt,

The syntax is ` .query().order(by: "date DESC, Id ASC")`, I hadn't thought of chaining them together like in your top example, it's a good idea.  We will put that in for the next release as it is far more logical.

Thanks
Adrian

**Comment by mattvb91** [comment]
Wow its amazing I always manage to miss the most obvious solution (in hindsight). Works! Happy to close this if needed. Thank you

Do you guys accept pull requests for documentation?

**Comment by editfmah** [comment]
Absolutely we do!  Anything that helps us out is always welcome.

**Comment by editfmah** [comment]
Implemented in v2.1.3
