### ISSUE TITLE
"Between" clause for NSDates not working

### ISSUE THREAD

**Issue by MeteC** [editfmah/sharkorm#69]
Hi, small concern really, but trying to use BETWEEN in a where clause for date values isn't working for me if I use something like:

    NSString* query = [NSString stringWithFormat:@"dateVal BETWEEN %@ AND %@",startDate, endDate];
    SRKResultSet* results = [[[TestObject query] where:query] fetch];

Where `startDate`, `endDate`, and `dateVal` are all `NSDate` objects.

However if I use

    NSString* query = [NSString stringWithFormat:@"dateVal BETWEEN %f AND %f",[startDate timeIntervalSince1970], [endDate timeIntervalSince1970]];
    SRKResultSet* results = [[[TestObject query] where:query] fetch];

 then it's fine. So this might not be an issue so much as a feature request.. however given the excellent support in other areas for objects like `NSDate`, I thought this might be worth flagging. Especially since being able to use BETWEEN on date objects in this fashion requires the user to know that NSDates are stored as their `[date timeIntervalSince1970]` value in the underlying database, which isn't obvious (and may not always be true). Thanks!

**Comment by editfmah** [comment]
Hi @MeteC 

It should totally work like that (with just NSDate objects),  so if it is not, then it is a bug.  We are just trying to sort out our new build (lots of things broke and the tests are failing).  But we will look into the bug as soon as we can.

Thanks
Adrian

**Comment by editfmah** [comment]
Hi @MeteC,

I've been testing this and can't see a problem.  My Unit test is below, does this meet you expectations?

```objective-c
- (void)test_date_parameters {
    
    [self cleardown];
    
    // fisrt should be excluded form the results
    MostObjectTypes* mo0 = [MostObjectTypes new];
    mo0.date = [NSDate date];
    [mo0 commit];
    [NSThread sleepForTimeInterval:0.1];
    
    NSDate* start = [NSDate date];
    [NSThread sleepForTimeInterval:0.1];
    
    MostObjectTypes* mo1 = [MostObjectTypes new];
    mo1.date = [NSDate date];
    [mo1 commit];
    
    [NSThread sleepForTimeInterval:0.1];
    
    MostObjectTypes* mo2 = [MostObjectTypes new];
    mo2.date = [NSDate date];
    [mo2 commit];
    
    [NSThread sleepForTimeInterval:0.1];
    int64_t count = [[[MostObjectTypes query] whereWithFormat:@"date >= %@ AND date <= %@", start, [NSDate date]] count];
    
    XCTAssert(count == 2, @"query with NSDate parameters failed");
    
}
```

**Comment by editfmah** [comment]
@MeteC, ah!  I totally see your problem now.  You need to use whereWithFormat, as it supplies the objects as parameters and encodes them properly for SQLite.  Your way is just making a string outside of Shark which SQL has no idea how to deal with as it will compare numbers with strings.  See example above to fix.

**Comment by MeteC** [comment]
Hi Adrian, indeed I was using just where, thanks!
