### ISSUE TITLE
SRKResultSet removeAll unsafe when relationships removed

### ISSUE THREAD

**Issue by MeteC** [editfmah/sharkorm#70]
I have an object class, a collection class, and a relationship class, all of which subclass SRKObject. I create relationships for 1 collection and 3 objects, commit it all, then I call `remove` on the first object. I then fetch all the relationships for that collection, giving me an `SRKResultSet` that looks like:

    (
    "<null>",
    "tag 2 / date 2017-03-29 21:54:53 +0000",
    "tag 3 / date 2017-03-28 21:54:53 +0000"
    )

(To clarify, I call `fetch` on my relationships table like 
`[[[TestRelationship query] whereWithFormat:@"collection = %@", self] fetch]`, 
then create a new `SRKResultSet` of objects using 
`[[SRKResultSet alloc] initWithArray:[relationships valueForKey:@"object"]]`)

So the SRKResultSet contains an NSNull object, which is fine, but then if I call removeAll on that SRKResultSet, I crash with 

    -[NSNull remove]: unrecognized selector sent to instance 0x1b62c3ef8

Guess this could be a very easy fix by just type checking in the loop in SRKResultSet#removeAll - unless there's a philosophy behind not doing that..? :-)

**Comment by editfmah** [comment]
That doesn't look much like a SRKResultSet, which is a subclass of NSArray.  That looks like a raw result or a call to distinct which are just `<Array<Dictionary>>` and `<Array>` retrospectively.

Can you provide the call which results in the SRKResultSet?

**Comment by editfmah** [comment]
The Philosophy is that there can never be anything other than an object in the result set, so that should not be an issue.  Because every entry is the result of a row in the database.

**Comment by editfmah** [comment]
Ah, sorry.  Didn't see your edit.

Basically, yeah, don't do that.  I should have made initWithArray private, you need to query to get objects and remove them.

I am slightly confused by your example.  If you were to take Person -> Address where you wanted to clean up all people for an address then you would use the following.

```
Address* add1 = [[[[Address query] where:@"name='some address'"] fetch] firstObject];

// Where Address has the code

- (BOOL)entityWillDelete {
     [[[[Person query] whereWithFormat:@"address = %@", self] fetch] removeAll];
     return YES;
}
```

[add1 remove];

Have I understood how you wanted to tackle this?

**Comment by MeteC** [comment]
Hi, sorry I put this in an edit before I noticed you'd responded already :) That is:

I call fetch on my relationships table like

    [[[TestRelationship query] whereWithFormat:@"collection = %@", thisCollection] fetch],
then create a new SRKResultSet of objects using

    [[SRKResultSet alloc] initWithArray:[relationships valueForKey:@"object"]])

(`TestRelationship` has properties `collection` and `object`)

So the query is returning a valid `TestRelationship`, but that relationship-object has `NSNull` as the value for it's `object`, since I removed that. Ok so my problem is I'm creating an array of those objects then basically casting it to SRKResultSet. My bad - I'll perform my own type checking on the initial returned SRKResultSet of relationship objects, before trying to create my own SRKResultSet manually!

**Comment by MeteC** [comment]
Ah - entityWillDelete is absolutely the right way to go, thanks!

**Comment by editfmah** [comment]
Ah no, I wasn't quite meaning that.  It was that you should tackle it from the inverse of the relationship.  e.g.

[[[[Collection query] whereWithFormat:@"Id = %@", self.collection] fetch] removeAll];

**Comment by editfmah** [comment]
or:

[[Collection objectWithPrimaryKey:self.collection] remove];

**Comment by MeteC** [comment]
yeah the magic trick was to put this in TestObject:

    - (BOOL) entityWillDelete
    {
      // also remove all relationships
      [[[[TestRelationship query] whereWithFormat:@"object = %@", self] fetch] removeAll];
      return YES;
    }

As you say, tackling it from the inverse. This way when I remove the object, I also remove all relationship entries. The collection remains but no longer "contains" that particular object...

**Comment by editfmah** [comment]
Cool, as long as you are up and running again.  We will add "more relationship" examples to the documentation list.

**Comment by MeteC** [comment]
Thanks!

And sorry I'm aware I've not done a good job of explaining, I should have said my classes for the Object, Collection, and Relationship concepts are just TestObject, TestCollection, and TestRelationship - and that I'm using a many-to-many relationship so that's why I'm using a 3rd table, TestRelationship, to manage those. (Slow morning over here...)

**Comment by editfmah** [comment]
Ha that's cool, I was being a bit slow too! :)
