### ISSUE TITLE
SRKUtilities assuming null ID is NSString

### ISSUE THREAD

**Issue by MeteC** [editfmah/sharkorm#71]
Hi again (sorry! ;-))

Been running into this one a bit today:

    failed: caught "NSInvalidArgumentException", "-[NSNull cStringUsingEncoding:]: unrecognized selector sent to instance 0x10e7b1130"
    (
	0   CoreFoundation                      0x000000010e4f2d4b __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x000000010df5421e objc_exception_throw + 48
	2   CoreFoundation                      0x000000010e562f04 -[NSObject(NSObject) doesNotRecognizeSelector:] + 132
	3   CoreFoundation                      0x000000010e478005 ___forwarding___ + 1013
	4   CoreFoundation                      0x000000010e477b88 _CF_forwarding_prep_0 + 120
	5   ASIGNCore_Tests                     0x000000011a2c67f9 -[SRKUtilities bindParameters:toStatement:] + 3625
	6   ASIGNCore_Tests                     0x000000011a1e6414 -[SharkORM performQuery:rowBlock:] + 11972
	7   ASIGNCore_Tests                     0x000000011a1e7596 -[SharkORM fetchEntitySetForQuery:] + 198
	8   ASIGNCore_Tests                     0x000000011a2d27c3 -[SRKQuery fetch] + 915

Caused by line 271 in SRKUtilities.m

    sqlite3_bind_text16(statement, paramCount, [sId cStringUsingEncoding:NSUTF16StringEncoding],@([sId lengthOfBytesUsingEncoding:NSUTF16StringEncoding]).intValue , SQLITE_TRANSIENT);

I can get this reliably by setting up a relationship (e.g. Department & Person), then calling `[department remove]`, and then querying with 
`[[[Person query] whereWithFormat:@"department = %@", department] fetch];`

It seems SRKUtilities is assuming that if an Id is not an NSNumber, it must be an NSString - but in the case of a removed object it can also be NSNull? 

SHARK_DATE              20170106
SHARK_VER               2.01.01

**Comment by editfmah** [comment]
Humm, that is an interesting one.  I'm surprised it has not come up before to be honest.  Although it is quite a unique situation in that you are asking for record which matches with nothing on the right.   But I was under the impression that when it came to binding I selected the bind, based on the object being bound.  Null and all.  But regardless, i'll take a look.  Might be a few days until it gets fixed, as we are still trying to clear up the mess after the last few changes for better swift3 interoperability.

**Comment by editfmah** [comment]
"Fixed", or ignored if you like in the new version v2.1.2
