### ISSUE TITLE
Problem with LEFT JOINs

### ISSUE THREAD

**Issue by Parkyprg** [editfmah/sharkorm#74]
There is a problem with aliases when using joins.

Take this simple example:

###SRKObject Department###
@property NSString *name;

###SRKObject Person###
@property NSString *name;
@property Department *dep;

Trying to fetch a person using a department name will fail:

`[[[Person query] whereWithFormat:@"dep.name = %@", @"TestDep"] fetch];`

[Executed query]:
`SELECT Person.name as result$name, Person.Id as result$Id, Person.dep as result$dep FROM Person  LEFT JOIN Department as query_auto_join_dep ON Person.dep = query_auto_join_Department.Id  WHERE query_auto_join_dep.name = ?   `

[Error Message]: 
`no such column: query_auto_join_Department.Id`

On LEFT JOIN, the alias is named after the field name (dep), but on actual join, the class name is used (Department).

**Comment by Parkyprg** [comment]
This was probably overlooked till now because the variable name was the same as object name.
And since queries are case-insensitive, this will run just fine:

`SELECT Person.name as result$name, Person.Id as result$Id, Person.department as result$dep FROM Person LEFT JOIN Department as query_auto_join_department ON Person.dep = query_auto_join_Department.Id WHERE query_auto_join_department.name = ?`

**Comment by editfmah** [comment]
Looking at it now, i've poked around in that area but nothing should have changed too much.  Just trying to get the issue simulated.

**Comment by Parkyprg** [comment]
Yep. The issue is easily replicated if you create a child object and give it a different name than the object name.
Then try to do a join query on that field.

**Comment by editfmah** [comment]
This has now been fixed and checked in.  Will go into the next release.  I t would seem to have always been a problem which was just not discovered randomly.
