### ISSUE TITLE
Commit method is not called on child objects.

### ISSUE THREAD

**Issue by Parkyprg** [editfmah/sharkorm#75]
If there is a relation between 2 objects, calling commit on the parent one will not call the override commit on the second.

###SRKObject Department###
@property NSString *name;

###SRKObject Person###
@property NSString *name;
@property Department *dep;

If I call [person commit], department will be persisted in the database, however, commit method from my Department object is not being triggered. Commit from Person works ok.

**Comment by editfmah** [comment]
When you say "commit method from my Department object is not being triggered", but it is still getting persisted.  Embedded objects have the `_rawCommitWithObjectChain` method called, and not the standard `commit`.

Are you overloading the commit method?

**Comment by Parkyprg** [comment]
Yes. I am overloading the commit method for the child object.
But if I call commit on the parent, the method is not called on the child.

**Comment by editfmah** [comment]
Yeah, as far as I know it never was.  Because we use the _rawCommit method.  this was put in a few years back when we introduced transactions.  I don't think that has changed has it?  Is this old code?

**Comment by Parkyprg** [comment]
No, I am running the latest one - 2.1.3

**Comment by editfmah** [comment]
What I meant sorry, was were you doing this before in the previous version and it worked?  Or have you just added this code?

**Comment by Parkyprg** [comment]
This was the first time I used it on a child object.

**Comment by editfmah** [comment]
Yes, this is by design.  But should it be?  I'm not sure.  Maybe, we need new methods, `entityWillCommit` or something?  we already have them for insert,update,delete.
