### ISSUE TITLE
Question on commit operation for lightweight objects

### ISSUE THREAD

**Issue by Parkyprg** [editfmah/sharkorm#76]
Say I have an object with 2 properties - A and B.

What happens if I fetch an object using fetchLightweightPrefetchingProperties for just property A and then immediately call a commit on the object?

Will B be persisted as nil in the database?

**Comment by editfmah** [comment]
No, lightweight objects are sterile.  They cannot be persisted back into the database at all.  I did consider a query to fill in the blanks, but decided against it because it was way too complicated.

**Comment by Parkyprg** [comment]
Thank you for your prompt reply!
