### ISSUE TITLE
Crashing on [modelObject commit], when model class is NSArray.

### ISSUE THREAD

**Issue by diliplilaramani** [editfmah/sharkorm#78]
Crashing on [modelObject commit]. Able to fetch all the values via modelObject. But Its crash on commit.

//ModelClass.h

@property (strong, nonatomic) ChatFlightCostModel *cost;
@property (strong, nonatomic) NSArray<ChatFlightLegModel*> *legs;

Crash logs:

-[ChatFlightLegModel encodeWithCoder:]: unrecognized selector sent to instance 0x608000118780

2017-04-07 16:05:13.659 tripeasel[2719:9608971] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[ChatFlightLegModel encodeWithCoder:]: unrecognized selector sent to instance 0x608000118780'

**Comment by editfmah** [comment]
Hi @dilipajm 

You are trying to persist an array of non-serialisable values.  But more to the point, that use case is not the way we would suggest you structure your data models.

Better to have a Model* property in the ChatFlightLegModel* class, therefore creating a relationship in the same way you always would in a RDBMS.

NSArrays & Dictionaries can contain any number of arrangements of Strings,Numbers,NSNull, but custom classes are tricky, you need to ensure they support NSKeyedArchiver, but that is bad practice as it is not very tolerant of model changes and adaptions.

Best to stick with the standard way of dealing with child data and have a hierarchical data structure through relationships.

**Comment by diliplilaramani** [comment]
Got it @editfmah. But I am using [KeyValueObjectMapping](https://github.com/dchohfi/KeyValueObjectMapping) for mapping json to model. Which suggest below code for my json. What do you suggest, how to handle json to model?

`          DCParserConfiguration *config = [DCParserConfiguration configuration];
            
            DCArrayMapping *mapper = [DCArrayMapping mapperForClassElements:[TRChatFlightLegModel class] forAttribute:@"legs" onClass:[TRChatFlightMessageModel class]];
            
            [config addArrayMapper:mapper];
            
            DCKeyValueObjectMapping *parser = [DCKeyValueObjectMapping mapperForClass:[TRChatTypeFlightsModel class] andConfiguration:config];
            
            TRChatTypeFlightsModel *chatTextModel = [parser parseDictionary:message.data.message];`

**Comment by editfmah** [comment]
Right I see,  well with nearly any ORM there is no easy way to get it done with a single line of code.  So, what we do is expand the JSON into objects naturally and then iterate through those objects writing the values into the SRKObject structure.  That way there is no need to match the JSON structure in the model and you retain some flexibility to perform processing on the values before writing.

**Comment by diliplilaramani** [comment]
Hi @editfmah , thanks for answering. I have uploaded my question-error in detail on stackoverflow. Can you please look into it and give me some advice? I think this is the common json structure everyone uses with models. Thanks for your support.

http://stackoverflow.com/questions/43320601/not-able-to-use-one-to-many-relationship-in-sharkorm

**Comment by diliplilaramani** [comment]
Solved. Thanks @editfmah for the help. 

Answer posted here - http://stackoverflow.com/questions/42694806/im-using-keyvalueobjectmapping-developed-by-dchohfi-but-facing-issue-in-mappin
