### ISSUE TITLE
Dynamic variable like Int?, Bool? how to get it work and why do I need dynamic ?

### ISSUE THREAD

**Issue by ormaa** [editfmah/sharkorm#79]
Hi,

I have this class :
class myClass: SRKObject {

    dynamic var id_bpu : Int = 0 // OK
    dynamic var label : String? = nil  // OK
   dynamic var value1: Int? = nil // KO. I can replace it by NSNumber.
   dynamic var value2: Bool? = nil // KO. what can I use  to replace this ?

another question is : why I need to use dynamic prefix, to have the variable saved in database ?
in this web site :http://sharkorm.com the sample does not use dynamic prefix.

I believe that it is needed to manage the type on SharkORM side, but I would like to understand.

thanks for any feedback.
Olivier

**Comment by ormaa** [comment]
Sorry to add another question in my thread :

    dynamic var label : String? = nil

if I fill label with a value : "test value"
the label is not saved in the database.
only few variables are saved : the variable which are not nullable.

is it normal ?

**Comment by editfmah** [comment]
Hi @ormaa,

I'll try to answer your questions in order.

1)  The equivalent to a nullable bool will be an NSNumber again, using the .boolValue() method.  Zero being false, non-zero being true.

2)  The Dynamic was not originally required with the first version of swift (we will update our site to show this), but has become necessary to ensure compatibility with objective-c.  And as an additional bonus it will warn you which types cannot be dynamically dispatched.

3)  That should work, in that we have unit tests with almost the same specification:

`dynamic var SwiftTestString : String?`

The difference being, the assignment with nil which I can't see having an effect.  Does the column get created in the table? and is it of the correct type?

**Comment by ormaa** [comment]
Hi, 

thanks for feedback.
yes, the column were created properly, the type is correct : TEXT for the String?
content is = null in the .db file

I will try to isolate my code, and my class to be saved in database, and will publish the code here.

**Comment by editfmah** [comment]
That is fascinating, as normally the issues arise from the inspection of the class type not recognising the appropriate type.  I'm just going to run up our unit test to have a look.

**Comment by ormaa** [comment]
Hi,

here is some code, allowing me to reproduce "easily" what I describe.

class SelectedBPU2: SRKObject {
    dynamic var id_bpu : Int = 0
    dynamic var ref_bpu : String = ""
    dynamic var label : String? = nil
    dynamic var label_description : String = ""
    dynamic var fk_id_unit: NSNumber? = nil
    dynamic var has_hood: NSNumber? = nil // will be a bool ! how can I know that when reading my code ?
    
    public func toBpu() -> Bpu
    {
        let bpu = Bpu()
        
        bpu.id_bpu = id_bpu
        bpu.ref_bpu = ref_bpu
        bpu.label = label
        bpu.description = label_description
        bpu.fk_id_unit = fk_id_unit as Int?
        bpu.has_hood = (has_hood == 1) ? true:false // this is bas, has_hood should be able to be nil
        return bpu
    }
    public init(bpu: Bpu) {
        super.init()
        
        id_bpu = bpu.id_bpu
        ref_bpu = bpu.ref_bpu
        label = bpu.label
        label_description = bpu.description
        fk_id_unit = bpu.fk_id_unit as NSNumber?
        has_hood = (bpu.has_hood == true) ? 1 : 0  // this is bas, has_hood should be able to be nil
    }
}

the class : Bpu is a normal class, inheriting from nothing ! and I cannot inherit from SRKObject in class Bpu.

I use that code (code 1) :
        let datas = BpuRepository().getBpus()
        // here, I have 180 objects, with all variable filled, except this one :  has_hood is nil.

        let obj = SelectedBPU2(bpu: datas[0])
        //        obj.id_bpu = 2
        //        obj.ref_bpu = "test"
        //        obj.label = "test2"
        //        obj.label_description = "test3"
        //        obj.fk_id_unit = 1234
        //        obj.has_hood = 1
        
        print(obj.label!) // crash here
        obj.commit()
        print(obj.id)
        print("read in database completed")
        
that code (code 2) :
        let obj = SelectedBPU2()
               obj.id_bpu = 2
                obj.ref_bpu = "test"
               obj.label = "test2"
                obj.label_description = "test3"
                obj.fk_id_unit = 1234
                obj.has_hood = 1
        
        print(obj.label!) // crash here
        obj.commit()
       // do not crash
Note : if I remove dynamic var, and SRKObject in SelectedBPU2 class, the code 1 does not crash. but is not saved in database, for sure :o)

**Comment by ormaa** [comment]
Hi,

here is some code more easily to use on your side, which reproduce the issue.

        SharkORM.setDelegate(self)
        SharkORM.openDatabaseNamed("sharkDatabase")
        
        //let datas = BpuRepository().getBpus()
        let dd = Bpu0()
        let obj = SelectedBPU2(bpu: dd)
        print(obj.label!) // Crash here. but debugger display something in .label !!!
        obj.commit()
        print(obj.id)
        print("read in database completed")

classes :

open class Bpu0: SRKObject
{
    var id_bpu : Int = 0
    var ref_bpu : String = ""
    var label : String? = nil
    var fk_id_unit : Int? = nil
    var has_hood : Bool? = nil

    

    public override init( )
    {
        super.init()
        
        id_bpu = 12
        ref_bpu = "my ref"
        label = "my label"
        fk_id_unit = 876
        has_hood = nil
    }
}


class SelectedBPU2: SRKObject {
    dynamic var id_bpu : Int = 0
    dynamic var ref_bpu : String = ""
    dynamic var label : String? = nil
    dynamic var fk_id_unit: NSNumber? = nil
    dynamic var has_hood: NSNumber? = nil // will be a bool ! how can I know that when reading my code ?
    
    public func toBpu() -> Bpu0
    {
        let bpu = Bpu0()
        
        bpu.id_bpu = id_bpu
        bpu.ref_bpu = ref_bpu
        bpu.label = label
        bpu.fk_id_unit = fk_id_unit as Int?
        bpu.has_hood = (has_hood == 1) ? true:false
        return bpu
    }
    public init(bpu: Bpu0) {
        super.init()
        
        id_bpu = bpu.id_bpu
        ref_bpu = bpu.ref_bpu
        label = bpu.label
        fk_id_unit = bpu.fk_id_unit as NSNumber?
        has_hood = (bpu.has_hood == true) ? 1 : 0
    }
}


I believe that I need to have all casses using dynamic ? which is not possible in my case.
in reality, I cannot modify the Bpu class :o(

**Comment by ormaa** [comment]
seem to work well with the latest source, instead of taking the framework compiled in sample application.

:)
