### ISSUE TITLE
latest SharkORM in Swift 3.1  - Crash when using [String]?

### ISSUE THREAD

**Issue by ormaa** [editfmah/sharkorm#84]
Hi,

here is my configuration : 
Application in IOS 10.0, Swift 3.1, SharkORM latest (taken on 2017-05-17)

When I use in my Entity object a variable like this : 
    dynamic var list: [String]? = nil

the value is saved, but I cannot access to it without crash.

here is the sample code to reproduce it. please tell me if it is a bug, or if I make a mistake.

thank you
Olivier

class PersonSwift : SRKObject {
    
    dynamic var Name: String?
    dynamic var age: NSNumber?
    dynamic var department: NSNumber?
    
    dynamic var list: [String]? = nil
}

class ViewController: UIViewController {

    override func viewDidLoad() {
        super.viewDidLoad()

        let m1 = PersonSwift()
        
        m1.Name = "toto"
        m1.age = 12
        m1.list = ["coucou", "salut", "super"]
        m1.commit()
        
        let t: PersonSwift = PersonSwift.query().fetch().object(at: 0) as! PersonSwift
        print(t) // all value are restored properly, in a json format :
        /*
        {
            entity = PersonSwift;
            joins =     {
            };
            "pk column" = Id;
            "pk value" = 1;
            properties =     (
                {
                    name = age;
                    type = number;
                    value = 12;
            },
                {
                    name = Name;
                    type = text;
                    value = toto;
            },
                {
                    name = list;
                    type = text;
                    value = "[\n  \"coucou\",\n  \"salut\",\n  \"super\"\n]";
            },
                {
                    name = department;
                    type = unset;
                    value = "<null>";
            },
                {
                    name = Id;
                    type = number;
                    value = 1;
            }
            );
            relationships =     (
            );
        }
         */
        
        print(t.Name!)   // works well
        
        let list = t.list // Crash with this error :
        //2017-05-18 09:31:48.023 sharkTest[50872:1268703] -[__NSCFString count]: unrecognized selector sent to instance 0x608000070180
        //2017-05-18 09:31:48.040 sharkTest[50872:1268703] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSCFString count]: unrecognized selector sent to instance 0x608000070180'
        //            *** First throw call stack:
        //        (
        //        0   CoreFoundation                      0x000000010ddabb0b __exceptionPreprocess + 171
        //        1   libobjc.A.dylib                     0x000000010b694141 objc_exception_throw + 48
        //        2   CoreFoundation                      0x000000010de1b134 -[NSObject(NSObject) doesNotRecognizeSelector:] + 132
        //        3   CoreFoundation                      0x000000010dd32840 ___forwarding___ + 1024
        //        4   CoreFoundation                      0x000000010dd323b8 _CF_forwarding_prep_0 + 120
        //        5   libswiftCore.dylib                  0x000000010d3d684b _TFVs12_ArrayBufferg5countSi + 155
        //        6   libswiftCore.dylib                  0x000000010d3f82fd _TFSag5countSi + 29
        //        7   libswiftCore.dylib                  0x000000010d3f82c5 _TTWurGSax_s10CollectionsFS_g5countwx13IndexDistance + 21
        //        8   libswiftFoundation.dylib            0x000000010d9d426a _TFEsPs10Collection3mapurfzFzWx8Iterator7Element_qd__GSaqd___ + 378
        //        9   libswiftFoundation.dylib            0x000000010d9ed153 _TFs15_arrayForceCastu0_rFGSax_GSaq__ + 227
        //        10  libswiftFoundation.dylib            0x000000010d9b14e9 _TZFE10FoundationSa36_unconditionallyBridgeFromObjectiveCfGSqCSo7NSArray_GSax_ + 217
        //        11  sharkTest                           0x000000010af7bf34 _TFC9sharkTest14ViewController11viewDidLoadfT_T_ + 1972
        //        12  sharkTest                           0x000000010af7c1e2 _TToFC9sharkTest14ViewController11viewDidLoadfT_T_ + 34
        //        13  UIKit                               0x000000010bd08cca -[UIViewController loadViewIfRequired] + 1235
        //        14  UIKit                               0x000000010bd0910a -[UIViewController view] + 27
        //        15  UIKit                               0x000000010bbd163a -[UIWindow addRootViewControllerViewIfPossible] + 65
        //        16  UIKit                               0x000000010bbd1d20 -[UIWindow _setHidden:forced:] + 294
        //        17  UIKit                               0x000000010bbe4b6e -[UIWindow makeKeyAndVisible] + 42
        //        18  UIKit                               0x000000010bb5e31f -[UIApplication _callInitializationDelegatesForMainScene:transitionContext:] + 4346
        //        19  UIKit                               0x000000010bb64584 -[UIApplication _runWithMainScene:transitionContext:completion:] + 1709
        //        20  UIKit                               0x000000010bb61793 -[UIApplication workspaceDidEndTransaction:] + 182
        //        21  FrontBoardServices                  0x000000010fafc5f6 __FBSSERIALQUEUE_IS_CALLING_OUT_TO_A_BLOCK__ + 24
        //        22  FrontBoardServices                  0x000000010fafc46d -[FBSSerialQueue _performNext] + 186
        //        23  FrontBoardServices                  0x000000010fafc7f6 -[FBSSerialQueue _performNextFromRunLoopSource] + 45
        //        24  CoreFoundation                      0x000000010dd51c01 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
        //        25  CoreFoundation                      0x000000010dd370cf __CFRunLoopDoSources0 + 527
        //        26  CoreFoundation                      0x000000010dd365ff __CFRunLoopRun + 911
        //        27  CoreFoundation                      0x000000010dd36016 CFRunLoopRunSpecific + 406
        //        28  UIKit                               0x000000010bb6002f -[UIApplication _run] + 468
        //        29  UIKit                               0x000000010bb660d4 UIApplicationMain + 159
        //        30  sharkTest                           0x000000010af7d567 main + 55
        //        31  libdyld.dylib                       0x000000010f38c65d start + 1
        //        32  ???                                 0x0000000000000001 0x0 + 1
        //        )
        //        libc++abi.dylib: terminating with uncaught exception of type NSException
            
        
        print("ok")
    }
    }

**Comment by ormaa** [comment]
Hi,

in order to help, here is some code which does not crash, but I still cannot get the [String] : 

        m1.Name = "toto"
        m1.age = 12
        m1.list = ["coucou", "salut", "super"]
        m1.commit()
        
        let t = PersonSwift.query().fetch().value(forKey: "list")  //.object(at: 0)

        let t2 = t as! [Any]
        print(t2)
        /* display this in outut console :
         [[
         "coucou",
         "salut",
         "super"
         ]]
         */
        
        let t3 = t2[0] as! String
        print(t3)
        /* display this in console output
         [
         "coucou",
         "salut",
         "super"
         ]
 
         display this in debugging console :
         t3	String	"[\n  \"coucou\",\n  \"salut\",\n  \"super\"\n]"
         */

**Comment by editfmah** [comment]
Thanks @ormaa ,

Please bear with me, I'm out of the country right now and have limited access to the net.  I will look at this issue promptly but on the surface it looks like Swift 3.1 has broken all kinds of reflection from Objective-C code.

I will look into it and get back to you.

Thanks
Adrian

**Comment by ormaa** [comment]
oh, my mistake !

Got the sharkOrm.framework from the main web site - sample application.
it is an outdated file !

if I compile the source from GitHub : it works !

thanks
Olivier

**Comment by editfmah** [comment]
Okay, thanks for the update.  (note to self, must update that damn sample), but I am still thrashing out some weird issues with Swift 3.1 and our test cases.
