### ISSUE TITLE
save relationship fail in transaction

### ISSUE THREAD

**Issue by a363211861** [editfmah/sharkorm#90]
OK:
 for (PR_SecretAccountPassword *password in self.passwords) {
        password.account = self.account;
        [password commit];
    }

Fail:
[SRKTransaction transaction:^{
        
        for (PR_SecretAccountPassword *password in self.passwords) {
            password.account = self.account;
            [password commit];
        }
        
  } withRollback:^{}];

**Comment by editfmah** [comment]
OK:
A bug report with any information, description or even effort put into it.
Fail:
Your bug report

Note:
The following test passes, so would you like to try again with some detail or an explanation or with any attempted debugging?

```
- (void)test_loop_relating_objects_commited {
    
    [self cleardown];
    
    Department* d = [Department new];
    d.name = @"New Department";
    
    NSArray* people = @[[Person new],[Person new],[Person new]];
    
    [SRKTransaction transaction:^{
        
        for (Person* p in people) {
            p.department = d;
            [p commit];
        }
        
    } withRollback:^{
        XCTAssert(1 == 2, @"rollback block was triggered");
    }];
    
    ;
    
    XCTAssert(([[[Person query] whereWithFormat:@"department = %@", d] count] == 3), @"embedded object within loop failed");
    
}
```
