### ISSUE TITLE
Removall

### ISSUE THREAD

**Issue by siriussoftware** [editfmah/sharkorm#94]
Removeall crashes my ios application when  called on SrkResultSet with approx. 8000 rows. 

All other operations work perfectly fine.

**Comment by editfmah** [comment]
So, it is likely to be memory related.  Given that 8k objects can take a lot of space, each one has to be created to propagate events and trigger and code on the methods `entityWillDelete`, `entityDidDelete`.

You can either batch this operation, doing 1k at a time.
You can disable events for those objects if you don't actually need the event model to trigger in this instance.
Or you could manually execute the sql to clean these records up if you are not using event code anywhere.

More simply, you could use `fetchLightweight`, instead of fetch to retrieve smaller objects which consume less memory.

**Comment by siriussoftware** [comment]
I tried hatches. App crashed after during the 6th 1k batch. I disabled events.  I fetched lightweight. I banged my head on wall. Can not avoid the crash.

And yes, it is a memory issues. 

Can I issue direct sql commands using sharkorm.

**Comment by editfmah** [comment]
Yes, use [SharkORM executeSQL:@“DELETE FROM xyz WHERE blah=‘blah'" database:nil]

It sounds like you might need to wrap those batches into an autorelease pool if the operation is iterative and tight, then that memory is not getting freed.

Or your objects are referencing many other objects and memory usage is spiralling or there is some kind of infinite loop in referencing in the data structure.

**Comment by siriussoftware** [comment]
Auto release pool is wrapped around command. Objects do not reference any other objects.

I do believe I'm doing something wrong, but I cannot find it. 

Going to use raw sql and that should fix me. 

Thanks very much for help and suggestions

**Comment by editfmah** [comment]
It would be great if you could post some redacted code here, just for sanity purposes.  We have products that delete many 10k's of records in single ops.  And we hate for problems to go unresolved in the ORM.

**Comment by siriussoftware** [comment]
Yes. Will do.

**Comment by siriussoftware** [comment]
upcData.h

#import <Foundation/Foundation.h>
#import "SharkORM.h"

@interface UPCData : SRKObject

@property int rid;
@property int addedLocal;
@property(strong) NSString *upc;
@property(strong) NSString *vendorid;
@property(strong) NSString *vendoruom;
@property(strong) NSString *description;
@property int cost;
@property int retail;
@property(strong) NSString *vendorsku;
@property(strong) NSString *retailuom;
@property(strong) NSString *defaultuom;
@property(strong) NSString *upcskuflag;
@end



UpcData.m

@implementation UPCData

@dynamic rid;
@dynamic addedLocal;
@dynamic upc;
@dynamic vendorid;
@dynamic vendoruom;
@dynamic description;
@dynamic cost;
@dynamic retail;
@dynamic vendorsku;
@dynamic retailuom;
@dynamic defaultuom;
@dynamic upcskuflag;


+ (SRKIndexDefinition *)indexDefinitionForEntity {

    /* create an index definition object */
    SRKIndexDefinition *idx2 = [SRKIndexDefinition new];

    /* now specify which properties are going to be indexed */
    [idx2 addIndexForProperty:@"upc" propertyOrder:SRKIndexSortOrderAscending];
    return idx2;

}

@end




Elsewhere in the code....Both fail with memory issues

 @autoreleasepool {
        {
            [[[UPCData query] fetchLightweight] removeAll];
        };


        or

        SRKResultSet *r = nil;
        SRKResultSet *t = nil;
        int cc = 0;
        do{
            t = [[UPCData query] fetch];
            cc = t.count;
            r = [[[UPCData query] limit:500 ] fetch];
            bool t = [r removeAll];

        }while(cc > 0);

**Comment by editfmah** [comment]
if you had something like and this is psudo code.

```
while [[UPCData query] count] {
       @autoreleasepool {
              [[[[UPCData query] limit:1000] fetch] removeAll];
       }
}

```
You may find that works, as the release needs to be within the loop to free, a big op will still not allow the OS to free the memory.

**Comment by siriussoftware** [comment]
Your method supplied above does indeed work without error.
In my case with no referenced entities or needed triggers, I am going to stay with the RawSQL method.
I appreciate the sheer speed.

Thanks for great help and support
