### ISSUE TITLE
Create DB from .db file in workspace

### ISSUE THREAD

**Issue by stefanosisto** [editfmah/sharkorm#96]
Hello everybody! I want to preload a preload.db file in my assets and create a new db, called pippo starting from preload.db.

The users need to update and manage stuff in pippo so just the first time they use the app i want to create the load the db from preload.db.

Do you think is possible?

**Comment by editfmah** [comment]
Easiest thing to do would be to copy the pre-load db out of the bundle and name it pippo, then start the ORM.

Other than that, you might want to look at attaching the second database and then copying the data from one to the other.

**Comment by stefanosisto** [comment]
No, the copy is just on the launch. Then the user will use only pippo db. With some update, i need to change something in preload.db so i need to merge the db without losing some property on pippo db...!

**Comment by editfmah** [comment]
So are you saying that preload will be static and pippo will hold mutable data?  because you can use the "database" property on the objects and have some point to preload and some to pippo.

**Comment by stefanosisto** [comment]
Okok. Thanks for the suggestion.
Yes. Preload is static and pippo has mutable data.
So the first time i'm creating pippo copyng preload. And the user interact only with pippo.
When I will release a new update, i will change some property on pippo copyng from preload! But not all the properties :)

**Comment by editfmah** [comment]
Yeah, so just base those objects on a different database:

```
@objc class PersonSwift : SRKObject {
    
    @objc internal dynamic var Name: String?
    @objc internal dynamic var age: NSNumber?
    @objc internal dynamic var department: DepartmentSwift?
    
    override class func storageDatabaseForClass() -> String {
       return "preload"
    }
    
}
```

**Comment by stefanosisto** [comment]
Thanks for all! I will write if I need other help!
