### ISSUE TITLE
Trouble with SharkORM - UserDefaults

### ISSUE THREAD

**Issue by stefanosisto** [editfmah/sharkorm#97]
Hello!
I have 3 table with 5500 row for each table.

I'm parsing a json with this 16k entities and i'm calling Transaction { let x..... x.commit() }
On new iphone, i can parse all in mmm 10 seconds. In the oldest one (iphone 5S) it's like 2 minutes.
I tried:
-DispatchQueue.global().async { function in which I have transaction } .. it finish in 1:40 but it's still inserting rows.
-DispatchGroup = split the json in 2 jsons,  group.enter(), DispatchQueue.global.async {function in which I have transaction on first half, group.leave()} group.enter(), DispatchQueue.global.async {function in which I have transaction on second hal, group.leave()}, still 1:40.

Nothing works to reduce time impact.
Can you help me? How can I manage the queue to make async 16k commit to reduce time?

**Comment by editfmah** [comment]
So top tips are.

Disable the event model if it is not needed that will speed things up a lot.  Batch inserts to around 1k objects at a time.

Minimise use of indexes on the target tables, if you are indexing strings use a no-case index if appropriate.

Don't use String primary key objects if you are.

But the event model is the slowest part of the ORM.

**Comment by stefanosisto** [comment]
I'm not using the indexes. I'm using only default property id.
Can u tell me more about the event model?

**Comment by stefanosisto** [comment]
Ah, what about UserDefault = if i'm using sharkORM with dispatchQueue {transaction .....}, the sync method of UserDefaults doesn't synchronize..

**Comment by editfmah** [comment]
I think that's because they have to be synchronised on the main thread.
